# Generated by Django 2.2.2 on 2019-06-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='medecin_type',
            field=models.CharField(choices=[('coach', 'Coach'), ('psychologue', 'Psychologue')], default='Admin', max_length=10),
        ),
    ]
