# Generated by Django 2.2.2 on 2019-06-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0002_auto_20190629_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
    ]
