# Generated by Django 2.2.2 on 2019-06-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medecin', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naiss',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sexe',
            field=models.CharField(blank=True, choices=[('M', 'Homme'), ('F', 'Feme'), ('O', 'Autre')], default='', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telpephone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
